// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfdF-VXBAOgUiAi1liIzyx8SuAB5CHcmo',
    appId: '1:1090004440164:web:6f4eb1c7016de319f7fb71',
    messagingSenderId: '1090004440164',
    projectId: 'practice2-ffd60',
    authDomain: 'practice2-ffd60.firebaseapp.com',
    storageBucket: 'practice2-ffd60.appspot.com',
    measurementId: 'G-XXM1HPWS08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8aIZA_RxNd9VhVOIc4TiQaQ2B-tJgDnM',
    appId: '1:1090004440164:android:b5ad94d71b51a27ef7fb71',
    messagingSenderId: '1090004440164',
    projectId: 'practice2-ffd60',
    storageBucket: 'practice2-ffd60.appspot.com',
  );
}
